### ISSUE TITLE
7tv emotes from followed streams showing global

### ISSUE THREAD

**Issue by bitteL3BN** [fgl27/SmartTwitchTV#152] opened 2023-06-16 08:59 UTC
**Describe the bug**
I see 7tv emotes from followed channels in channels where they aren't activated. Text gets autotranslated to the 7tv emote even if the streamer doesn't have it in their emoteslots.

**To Reproduce**
1. Go to a stream with a specific 7tv emote activated that's not activated in another stream 
2. Go to the other stream without the emote 
3. Type the text for the emote
4. See the emote in chat although it should just be text

**Expected behavior**
"7tv emote cache" should be different for every stream I watch. I only want to see the emotes in chat that the streamer has added. Not the ones from other streams I follow.
 
 **Device:**
 - TV Manufacture Device: Nvidia Shield Pro

**Comment by fgl27** [comment] 2023-06-16 16:50
will revise the implementation next time I have some time

**Comment by fgl27** [comment] 2023-06-18 03:26
this was fixed on the last version test let me know.

**Comment by bitteL3BN** [comment] 2023-06-18 13:10
Thanks, seems to work now. The only part which could be improved is that the old messages from the chathistory when you enter a channel rerender once the correct emotes are loaded. Would be a minor improvement but I think than it would be perfect. Don't know if that's possible to code and you understand what I mean (English isn't my first language).

**Closed** 2023-06-27 11:42 UTC
Labels: bug

**Comment by bitteL3BN** [comment] 2023-08-06 08:36
I don't remember if this is an issue that existed before those changes but I noticed that if I watch 2 streams (pip) with chat on on both of them only one chat has correctly loaded emotes while they appear just as plain text in the other.

**Comment by fgl27** [comment] 2023-08-06 14:18
Can't replicate that, maybe some custom emotes aren't loading due to api issue.

If you can reproduce that all the time open a issue with a way to reproduce.

**Comment by fgl27** [comment] 2023-08-06 14:30
> I don't remember if this is an issue that existed before those changes but I noticed that if I watch 2 streams (pip) with chat on on both of them only one chat has correctly loaded emotes while they appear just as plain text in the other.

Il this only affects custom emotes, I was looking before chat without it 

I'll take a look and fix it.

**Comment by fgl27** [comment] 2023-08-06 16:53
the missing emotes on one of the chats is resolved
