### ISSUE TITLE
Prohibited content, it is limited to your region or the official Twitch app

### ISSUE THREAD

**Issue by Deimos36Rus** [fgl27/SmartTwitchTV#232] opened 2024-10-28 23:09 UTC
**Describe the bug**
Previously, everything worked fine when using WARP in app AmnesiaWG. Literally 2 days ago, on absolutely all channels, he wrote to me "prohibited content, it is limited to your region or the official twitch application"

**To Reproduce**
Log in to the app and select any channel

**Expected behavior**
Stable operation when using WARP

 **Device:**
 - TV Manufacture Device: TV Box UGOOS AM6 PRO PLUS
 - Android TV Slimbox (Android 9.0)

**Additional context**
Twitch's account is fine. Everything works on the phone and PC. The problem started only recently and only when using WARP. Before that, everything had been working stably for months. When WARP is disabled, everything works.

**Comment by fgl27** [comment] 2024-10-29 10:42
If you have an app that blocks IPs and that prevents this app from working how is this app problem?

Try this one simple thing, uninstall that WARP this app goes back to work problem solved.

**Comment by Deimos36Rus** [comment] 2024-10-29 11:42
> If you have an app that blocks IPs and that prevents this app from working how is this app problem?
> 
> Try this one simple thing, uninstall that WARP this app goes back to work problem solved.

As far as I know WARP does not change the IP address, it only encrypts the data and uses a different DNS.
Apparently Twitch changed something on his part and now nothing works.
I would love to remove WARP, but I have to use it for certain reasons. But at the same time, I don't want to lose access to Twitch's best client.
I'm not blaming the app, I'm describing the error I encountered. Although before that, everything was perfect for me.
Maybe you can change something in the application to make everything work again.

**Comment by Deimos36Rus** [comment] 2024-10-29 11:58
I solved the problem by installing the exclusion of the twitch client from AmnesiaWG.
If there is an opportunity to refine the application in this direction, then it will be great. If not, then no.

**Comment by fgl27** [comment] 2024-10-29 12:37
> I solved the problem by installing the exclusion of the twitch client from AmnesiaWG. If there is an opportunity to refine the application in this direction, then it will be great. If not, then no.

How will that be possible? explain to me that, if there is a way I can take a look.

but for me is this simple...

If you install the X app and the X app causes a problem with the Y app, how can the problem be resolved in the Y app if the problem is with the X app?

It makes no sense to me that I can prevent one app from doing something. Try that developer and see what they have to say.

**Closed** 2024-10-29 12:42 UTC
Labels: Not an app issue
