### ISSUE TITLE
Audio channels overlap when a stream ends in multistream mode. Muted devices will automatically unmute as well

### ISSUE THREAD

**Issue by bossanovaorca** [fgl27/SmartTwitchTV#20] opened 2020-10-09 16:03 UTC
**Describe the bug**
When one of the 4 streams ends in a multistream, audio from another stream automatically starts playing on top of the current stream. I have also experienced cases where a stream ending in multistream mode unmutes the device

**To Reproduce**
1. Watch several streams in multistream mode
2. Wait for a stream to end?
3. Audio from multiple streams will start playing or if muted, the device will unmute automatically

it isn't consistent but I've had it occur often enough to see this pattern

**Expected behavior**
The audio channel should remain on the current stream only/keep the previous audio setting if overlaying audio. Muted devices should not unmute

 **Device:**
 - LG E8 TV, Nvidia Shield Pro

**Comment by fgl27** [comment] 2020-10-10 01:33
I did only found two minor issues, related to what you described but not what you described.

1. a display issue on the audio icon that show next to the streamer name, sometimes was wrong
2. If the stream that ended wasn't the main one (Main one is TOP left or top one when the Main one is big mode)... the audio may not change to a active one...

The idea of change the audio source is, if the audio is on the stream that ended the audio will switch to another, that is working fine for me at least after the above.

I don't think a app can change the device volume, or unmute it, the permission probably doesn't exist, you can check this app permission in playstore, change audio source or anything related to audio is not there.

If you can replicate a problem after updating the app let me know... To update the app just close it by holding the return key and reopen.

**Comment by fgl27** [comment] 2020-10-10 07:33
If you have access to a numeric keyboard, for example a computer keyboard or a remote that has numbers, I can share a app that closes a stream base on a key number (1234) press..

If you wanna test on yours device this issue more easily as that is how I test.

**Comment by bossanovaorca** [comment] 2020-10-11 01:57
I'll wait and see if I can still get this issue to occur after updating. It was already kind of inconsistent but it happened enough for me to open a ticket. Thanks for the quick response

**Comment by fgl27** [comment] 2020-10-11 11:19
OK let me know when you have manage to test in a conclusive way.

**Comment by bossanovaorca** [comment] 2020-10-12 00:58
Still not a consistent test but I encountered it again today while multistreaming. This time no channels went offline or anything though. Maybe it's related to ad breaks? I have no idea why but it seemed to be random...watching one channel in multistream mode and suddenly another one unmutes

**Comment by fgl27** [comment] 2020-10-12 01:05
Are you sure you did press a key?
That yours remote is randomly sending keys?

Only a key press can cause that. Left right on multi will change the audio source and show a sort warning in the screen.

So did you sow the warning. Also inform all I all before..



> If you can replicate a problem after updating the app let me know how, make sure to inform, what was the mode (4 streams same size or main one big), what was the position of the window that closed (On main window big if the main closes one will replace it as main), what was the audio source before, what is the audio source after, make sure you don't confuse the expected behavior of the audio source change when the stream that ended was the main audio source...

**Comment by fgl27** [comment] 2020-10-12 03:18
I have found a corner case and fix on the above... When a player restarted that player after the restart will have audio, a player restart like this happens do to a error or because it stopped do to a momentary internet issue or something related, on that case you can clear see the player back stop the player screen goes full black and the loading spinner show.

Don't know if is the case you need to answer all my question in order to me be able to understand the issue, even if is replay the question with another.

App version 264 (3.0.264) was released, update from play store to get that fix.

**Comment by fgl27** [comment] 2020-10-18 03:47
With this changes I believed is all OK now

https://github.com/fgl27/SmartTwitchTV/commit/63b451233e0a97eaf748305203122df5656b5e79
https://github.com/fgl27/SmartTwitchTV/commit/d525e32ffb80b1e4e6aed06d07c917f7df6b2a92
https://github.com/fgl27/SmartTwitchTV/commit/b243ec803bdf72db23c1ead5a31b8970148608d0
https://github.com/fgl27/SmartTwitchTV/commit/c30faef9562f228ae74d7ec3758b24ed4e7bc581

All of those was introduced in version 262

The big issue is the problem that twitch created by not sending a stream has ended sometimes, I believe they don't send because of the feature that they implemented to keep the stream alive in the case the streamer didn't intentionally ended it with is a nice thing but as most thing on twitch is a bugged thing, as sometimes the stream really endes but the server will not inform with will cause the app to restart the stream trying to fix the problem.

On the case the stream has ended or is unavailable (streamer has connection issues) the app will not receive any new content from the server as the stream for a moment and will try to restart the player to see if things get back to work as ins't possible to detect if the problem is local on the device or on the server, as a restart was causing the player that restarted to have audio that was the main bug...

All other fixes was cosmetic.

Let me know the behavior I can't find issues

**Closed** 2020-10-26 09:34 UTC

**Comment by bossanovaorca** [comment] 2020-10-27 14:44
thanks for fixing this!
