### ISSUE TITLE
Possible code regression with stream lagging

### ISSUE THREAD

**Issue by kurtdh** [fgl27/SmartTwitchTV#75] opened 2021-08-09 20:13 UTC
This problem just started happening recently, so I’m thinking it’s a code regression in one of the recent releases. 

When I’m watching a stream and I hit the fast forward button on my remote to open up chat, the stream lags for a second or two with the white spinning circle in the center of the screen. If I stay on that stream and close and reopen chat, it no longer lags the stream. It only lags the stream the first time chat is open after turning to that channel. 

If I open another stream while chat is already enabled, and then I press the fast forward button on the remote to close chat, it will lag the stream then too. But like before, it only happens the first time after first viewing a stream. Are you able to replicate this? This has never been a problem until recently. On the 2019 shield pro. I can include a video if that is helpful let me know.

**Comment by fgl27** [comment] 2021-08-10 05:48
No I can't reproduce on my shield.

**Comment by fgl27** [comment] 2021-08-10 05:57
see here https://www.youtube.com/watch?v=gnKI6h6CVOk

**Comment by fgl27** [comment] 2021-08-10 05:58
don't you have some accessibility service enabled?

**Comment by kurtdh** [comment] 2021-08-10 07:38
I do not have accessibility enabled. I figured it was one of my settings so I went through them one by one and I found the culprit. 

Go to settings and change default player quality from auto to source. 

Now try to replicate.

**Comment by fgl27** [comment] 2021-08-10 09:15
Yes I can see it now, that was introduced on 326, fixed on 327

**Closed by fgl27** 2021-08-10 09:15 UTC
