### ISSUE TITLE
App starts to black screen and cant do anything

### ISSUE THREAD

**Issue by twiikker** [fgl27/SmartTwitchTV#212] opened 2024-03-19 10:54 UTC
When i start app there is just following items.
Left top corner:
Refresh: Hold enter
Hold left for thumbnail options

Middle of screen:
Loading arrow-circle

Nothing happens if i press any buttons or hold enter to refresh
Killing app doesnt help
Clearing cache doesnt help
Clearing all data helps but need to apply all settings again

Happened yesterday and today again

**Screenshots**
![IMG_20240319_124425](https://github.com/fgl27/SmartTwitchTV/assets/79707092/8a9614da-4e68-4b49-b3ba-58f2d02a4e6a)

 
 **Device:**
 - Nvidia Shield pro 2017
 - Android 11

**Comment by fgl27** [comment] 2024-03-19 13:45
I don't know how to reproduce this.

Clean app data write down all changes you made and share so I can reproduce and fix it.

**Comment by djrick1994** [comment] 2024-03-20 00:18
I'm having the same problem with the app on my Google Chromecast with Google TV (4K model).
The problem started after the recent update.

It appears that the app is trying to load the screen with the live channels on the left and the stream preview on the right (I don't know the proper name of that specific screen).
I have only have this happen when starting the app, not when switching apps.

Reinstall or deleting user data only fixes it temporarily.
It is also not happening every time the app starts and I haven't been able to reproduce the problem manually (force closing the app or rebooting the Chromecast when the app was closed while in different menus or playing media).

I'll keep an eye out for some kind of pattern in behavior and app state that might cause this issue.

**Comment by fgl27** [comment] 2024-03-20 01:16
this icon 
![image](https://github.com/fgl27/SmartTwitchTV/assets/13755892/7c948150-c47e-4172-9b22-30baa11231d2)

is part of the dialogs that show when a playback ends

So the issue is when you are watching a stream you close the app and when you return the stream has ended and those dialogs try to show and brick the app.

Will try to reproduce it as a simple fix, is just not that easy to cause it.

If anyone has a better idea of how to let em know.

**Comment by djrick1994** [comment] 2024-03-20 01:35
For what its worth, on my Google TV it doesn't show that icon, but a spinning circle that is not completely closed.

![IMG20240320021939](https://github.com/fgl27/SmartTwitchTV/assets/24964188/9fe62ca7-e224-437b-850f-2df0e35b4e75)

I haven't been able to reliably reproduce the error, but from my testing it appears that the problem only occurs when the app tries to load the screen with the live channels on the left and preview on the right. When the app starts on any other screen (like a channel or the user select page) then everything works without a problem.

**Comment by fgl27** [comment] 2024-03-20 01:39
I can't find a way to reproduce that issue or the first comment issue.

below screen @djrick1994 ? the app can't boot to that screen, is something you must open manually after the app has finished loading.

So maybe is the screen you were on before you opened below, do you remember?

![image](https://github.com/fgl27/SmartTwitchTV/assets/13755892/75aad02e-45ec-4d1c-9e30-73de9c1f8a4f)

**Comment by fgl27** [comment] 2024-03-20 01:46
all with this problem share the changes you make to the app

language, settings, and player controls any changes you made.

Is something related, also the screen you were on before the app was closed, and if there was a stream vod or clip playing?

**Comment by djrick1994** [comment] 2024-03-20 02:18
@fgl27 That is indeed the screen that I'm referring to. Is there a proper name that I can use when referring to that particular screen?

I can't remember exactly what the state of the app was before the problem occurs (playing media or in menu).

> the app can't boot to that screen, is something you must open manually after the app has finished loading.

Usually it will either resume playback of the media that was playing or open the last menu (channel list, user channel, vod list, etc.), but there seems to be a specific set of circumstances where the app tries to open the screen as shown in your screenshot.

It is just after 3AM here so I will do the following:

I will open the preview screen as shown in your screenshot and I will select a stream of which I know for certain that it will end before I wake up.
I will turn off the Chromecast while the preview is playing using the standby button on the remote.
Tomorrow morning I will open the app and check if it will start normally or if it has triggered the issue.

I have a couple of things in mind that I will try tomorrow with the app in a mostly "vanilla" state.

**Comment by fgl27** [comment] 2024-03-20 02:42
I call it 'side panel' there is the menu side panel that you use to change screen, and the user live side panel from that image I shared before.

I will revise I only remember anything related to open the side panel being triggered by a key, the app can't open it without a interaction.

Example key number 3 if you have an remote with number will open/close the user live side panel.

Any way report your findings, thanks for the help 

Will revise all shared here to see if I can understand were this problem is.

**Comment by twiikker** [comment] 2024-03-20 06:14
> this icon ![image](https://private-user-images.githubusercontent.com/13755892/314307362-7c948150-c47e-4172-9b22-30baa11231d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MTU0MDMsIm5iZiI6MTcxMDkxNTEwMywicGF0aCI6Ii8xMzc1NTg5Mi8zMTQzMDczNjItN2M5NDgxNTAtYzQ3ZS00MTcyLTliMjItMzBiYWExMTIzMWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA2MTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMGNkZmNlOWNjNjc3ZWQ3MzhhNjNjYzMyYTlhYjNlYzZlMTc0OGYwOWFmZTgxZGUxZTNlZTMwZDQ4YTlhNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WdET9OATeh177AKw2HvxuQL4DFMDs5c8kv5E4mGC8vY)
> 
> is part of the dialogs that show when a playback ends
> 
> So the issue is when you are watching a stream you close the app and when you return the stream has ended and those dialogs try to show and brick the app.
> 
> Will try to reproduce it as a simple fix, is just not that easy to cause it.
> 
> If anyone has a better idea of how to reproduce this, let me know.

I am 99% sure that i never leave stream running when i leave app. Also now is 3rd time this has happened and always happens when i start app for first time after night. Doesnt seem to happen when device is off/sleep for shorter period.

I will look at all settings next for you.

**Comment by twiikker** [comment] 2024-03-20 06:27
Settings walkthrough:
-activate account

-chat options:
--insert line to separate messages: no
--show total chatters or viewers: viewers
--highlight messages from streamer: yes

-customize interface:
--thumbnail quality: high
--enable app animations: no

-notification options:
--show streamer live notification: no

-warnings
--show an accessability service is running: no
(I havent had issue with this for past 5 months ive had this device. i only use it to disable netflix button on remote)

-always start app in user screen: yes
-single return press: yes
-default player quality: source

-preview thumbnail player settings
--all 5 first settings to no

-vod controls max time to 10min

99% of times i leave app to user live channel menu when i leave app

**Comment by djrick1994** [comment] 2024-03-20 10:25
So when I started the app this morning it started with the black screen and spinning circle as described before.
After a reset of the app I've tried to recreate multiple different scenarios to try and force this error state, but to no avail.
I've even tried using a test stream from an alt account to see if the stream going offline while the app is closed might trigger something, but that also didn't work.
I usually starts the app in the last visited menu, but it really looks like the app is sometimes trying to load the side panel on startup. Why it does that is something that I also don't understand.

As mentioned before I'll try to see if I can find some kind of pattern in the apps behavior.

In the mean time, here are the settings I usually change from the default app settings.

**App settings**

Account
- logged in

Chat options
- Insert a line to separate individual chat messages: No
- Background color difference between individual message: Enabled
- Show total logged in users on top of the chat or viewers: Show viewers
- Highlight message from the streamer: Yes
- Highlight your sent messages: Yes
- Clear chat, delete user message: No

Customize interface
- Enable app animations: Yes

Warnings
- Show 'an accessibility service is running' warning: No (I use a button remapper that needs to run as an accessibility function)

Automatically change player quality from source to auto when the player lags: No
Default player quality: Source

Start buffer size
- Lives start buffer: 0.1


**Chat settings inside player**

Video mode: Side by side, video and chat
Chat front size: 95%
Chat size: 20%
Chat delay: Based on latency to broadcaster


The Chromecast I'm using is running Android TV version 12 with the security updates from January 1st 2024.
The app language is English, but the Chromecast itself is set to Dutch.

If there is more info that you need, please let me know.

**Comment by fgl27** [comment] 2024-03-20 14:10
@djrick1994 @twiikker can you disable the accessibility service and see if that solves?

Make sure to keep notification on so you know nothing regarding accessibility is on.

If was a app issue I expect more reports, but we don't have it and you both are using button remappers

**Comment by djrick1994** [comment] 2024-03-21 10:19
Yesterday I've disabled the button remapper, disabled the accessibility service and enabled the accessibility service warning inside the app.
Used the app the whole day without any problems.
At the end of the evening I turned off the Chromecast while a stream was still playing.

This morning I opened the app using the icon on the Chromecast home screen after which it opened straight into the side panel screen with the spinning circle.

It almost appears that the error happens at random because in my testing I've had it happen a couple of times, but I was never able to reliably reproduce it, even when doing the exact same actions.

Is there any way to enable some kind of debug or verbose logging on our end to see what the app is trying to do?

**Comment by Walker-Twitch** [comment] 2024-03-21 12:56
> When i start app there is just following items. Left top corner: Refresh: Hold enter Hold left for thumbnail options
> 
> Middle of screen: Loading arrow-circle
> 
> Nothing happens if i press any buttons or hold enter to refresh Killing app doesnt help Clearing cache doesnt help Clearing all data helps but need to apply all settings again
> 
> Happened yesterday and today again
> 
> **Screenshots** ![IMG_20240319_124425](https://private-user-images.githubusercontent.com/79707092/314023945-8a9614da-4e68-4b49-b3ba-58f2d02a4e6a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjU2MTcsIm5iZiI6MTcxMTAyNTMxNywicGF0aCI6Ii83OTcwNzA5Mi8zMTQwMjM5NDUtOGE5NjE0ZGEtNGU2OC00YjQ5LWIzYmEtNThmMmQwMmE0ZTZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEyNDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5M2NiMjA5NzllYWYzM2NmZjZiNTU5MzZjNTVlZDdhMDY5NzkyMGQzMThhYzljY2VhMzE3NmJlZTVmMzgzZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mm6ybJVPqGTmGrFxk0jP1cunBHeHia-5U7XNl0dGsBg)
> 
> **Device:**
> 
> * Nvidia Shield pro 2017
> * Android 11

I also have the same problem.

I have tested the setting many times and found out that if you change this setting (shown in picture), the problem will occur.
![20240321_203914](https://github.com/fgl27/SmartTwitchTV/assets/164352973/b824698e-9e14-4257-a724-d8327af62d8c)

**Closed** 2024-03-21 13:52 UTC

**Comment by fgl27** [comment] 2024-03-21 13:55
I pushed an update, the change above to fix it.

It was a combination of settings Chat options 'Show viewers' and player settings chat 'Side by Side, video and chat' enabled at the same time.

**Comment by fgl27** [comment] 2024-03-21 13:56
Thanks All for the help!
